steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nexus-weaver-control-plane:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nexus-weaver-control-plane:latest']

images:
  - 'gcr.io/$PROJECT_ID/nexus-weaver-control-plane:latest'