version: '3.8'

services:
  control-plane:
    image: nexus-weaver/control-plane:latest
    container_name: nexus-weaver-control
    env_file:
      - ./services/control-plane/.env.production
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  kernel:
    image: nexus-weaver/kernel:latest
    container_name: nexus-weaver-kernel
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    environment:
      GRPC_PORT: 50051
      LOG_LEVEL: info
    ports:
      - "50051:50051"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    restart: unless-stopped

  dashboard:
    image: nexus-weaver/dashboard:latest
    container_name: nexus-weaver-dashboard
    env_file:
      - ./services/dashboard/.env.production
    ports:
      - "80:80"
    depends_on:
      - control-plane
    restart: unless-stopped

networks:
  default:
    name: nexus-weaver-network